import { 
  Mic, 
  Video, 
  Upload, 
  FileText, 
  CheckCircle, 
  Play, 
  Square, 
  Download, 
  Cpu, 
  Brain,
  BarChart,
  User,
  Briefcase,
  BookOpen,
  ArrowRight,
  Loader2,
  AlertCircle,
  Sun,
  Moon,
  Lock,
  Monitor,
  Settings,
  Camera,
  RefreshCw,
  Activity
} from 'lucide-react';

export const Icons = {
  Mic, 
  Video, 
  Upload, 
  FileText, 
  CheckCircle, 
  Play, 
  Square, 
  Download, 
  Cpu, 
  Brain,
  BarChart,
  User,
  Briefcase,
  BookOpen,
  ArrowRight,
  Loader2,
  AlertCircle,
  Sun,
  Moon,
  Lock,
  Monitor,
  Settings,
  Camera,
  RefreshCw,
  Activity
};

export const MOCK_CHART_DATA = [
  { subject: 'Technical', A: 120, fullMark: 150 },
  { subject: 'Communication', A: 98, fullMark: 150 },
  { subject: 'Problem Solving', A: 86, fullMark: 150 },
  { subject: 'Experience', A: 99, fullMark: 150 },
  { subject: 'Culture Fit', A: 85, fullMark: 150 },
  { subject: 'Adaptability', A: 65, fullMark: 150 },
];