import React, { useEffect, useState } from 'react';
import { AppStage, InterviewContextData, InterviewTurn, ReportData } from '../types';
import { generateFinalReport } from '../services/geminiService';
import { generatePDF } from '../services/pdfService';
import { Icons } from '../constants';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer } from 'recharts';

interface ReportStageProps {
  history: InterviewTurn[];
  context: InterviewContextData;
  setStage: (stage: AppStage) => void;
  darkMode: boolean;
  toggleTheme: () => void;
}

const ReportStage: React.FC<ReportStageProps> = ({ history, context, setStage, darkMode, toggleTheme }) => {
  const [report, setReport] = useState<ReportData | null>(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const data = await generateFinalReport(history, context);
        setReport(data);
      } catch (e) {
        console.error("Failed to generate report", e);
      }
    };
    fetchReport();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!report) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col items-center justify-center transition-colors">
        <Icons.Loader2 className="w-12 h-12 text-cyan-600 animate-spin mb-4" />
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white">Aggregating Analytics...</h2>
        <p className="text-slate-500 dark:text-slate-400 mt-2">Compiling technical scores, behavioral markers, and interview summary.</p>
      </div>
    );
  }

  const chartData = [
    { subject: 'Technical', A: report.categoryScores.technical, fullMark: 100 },
    { subject: 'Subject Knw.', A: report.categoryScores.subjectKnowledge, fullMark: 100 },
    { subject: 'Behavioral', A: report.categoryScores.behavioral, fullMark: 100 },
    { subject: 'Functional', A: report.categoryScores.functional, fullMark: 100 },
    { subject: 'Non-Functional', A: report.categoryScores.nonFunctional, fullMark: 100 },
    { subject: 'Communication', A: report.categoryScores.communication, fullMark: 100 },
  ];

  const getRecColor = (rec: string) => {
    switch(rec) {
      case 'STRONG_HIRE': return 'bg-green-600';
      case 'HIRE': return 'bg-emerald-500';
      case 'MAYBE': return 'bg-yellow-500';
      default: return 'bg-red-500';
    }
  };

  return (
    <div className="min-h-screen bg-slate-100 dark:bg-slate-900 transition-colors duration-300">
      
      {/* Nav Bar */}
      <div className="bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 px-6 py-4">
         <div className="max-w-6xl mx-auto flex justify-between items-center">
            <div 
              className="flex items-center space-x-2 cursor-pointer hover:opacity-80 transition-opacity"
              onClick={() => setStage(AppStage.HOME)}
            >
              <div className="bg-cyan-500 p-1.5 rounded-lg">
                  <Icons.Brain className="w-5 h-5 text-white" />
              </div>
              <span className="text-lg font-bold text-slate-900 dark:text-white">ProbeLensAI</span>
            </div>
         </div>
      </div>

      <div className="max-w-6xl mx-auto space-y-6 py-10 px-4">
        
        {/* Header */}
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm p-8 flex flex-col md:flex-row justify-between items-start md:items-center border border-slate-200 dark:border-slate-700">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Candidate Report</h1>
            <p className="text-slate-500 dark:text-slate-400 mt-1">Generated by ProbeLensAI • {new Date().toLocaleDateString()}</p>
          </div>
          <div className="flex flex-col md:flex-row items-start md:items-center space-y-3 md:space-y-0 md:space-x-4 mt-4 md:mt-0">
             <div className={`px-6 py-2 rounded-full text-white font-bold shadow-md ${getRecColor(report.recommendation)}`}>
               {report.recommendation.replace('_', ' ')}
             </div>
             <div className="flex space-x-2">
                <button onClick={toggleTheme} className="p-2 bg-slate-100 dark:bg-slate-700 rounded-lg text-slate-900 dark:text-white">
                  {darkMode ? <Icons.Sun className="w-5 h-5"/> : <Icons.Moon className="w-5 h-5"/>}
                </button>
                <button 
                onClick={() => generatePDF(report, context)}
                className="bg-slate-900 dark:bg-cyan-600 hover:bg-slate-800 dark:hover:bg-cyan-700 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition"
                >
                <Icons.Download className="w-4 h-4" />
                <span>Download PDF</span>
                </button>
             </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Summary Column */}
          <div className="md:col-span-2 space-y-6">
            <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-700">
              <h3 className="text-lg font-bold text-slate-800 dark:text-white mb-4 flex items-center">
                <Icons.FileText className="w-5 h-5 mr-2 text-cyan-600" /> Executive Summary
              </h3>
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed whitespace-pre-line">
                {report.summary}
              </p>
            </div>

            <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-700">
              <h3 className="text-lg font-bold text-slate-800 dark:text-white mb-4">Interview Log Analysis</h3>
              <div className="space-y-4">
                {report.turns.map((turn, i) => (
                  <div key={i} className="border-l-4 border-slate-200 dark:border-slate-600 pl-4 py-2 hover:border-cyan-500 transition-colors">
                    <div className="flex justify-between items-start">
                      <p className="font-semibold text-slate-800 dark:text-slate-200 text-sm">Q{i+1}: {turn.question}</p>
                      <span className={`text-xs px-2 py-0.5 rounded ml-2 whitespace-nowrap ${turn.analysis.technicalAccuracy > 70 ? 'bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-100' : 'bg-orange-100 dark:bg-orange-900 text-orange-800 dark:text-orange-100'}`}>
                        Score: {turn.analysis.technicalAccuracy}%
                      </span>
                    </div>
                    <p className="text-slate-500 dark:text-slate-400 text-sm mt-1 italic">"{turn.transcript.substring(0, 150)}..."</p>
                    <div className="mt-2 flex gap-2 flex-wrap">
                       {turn.analysis.keySkillsDemonstrated.map(s => (
                         <span key={s} className="text-[10px] bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 px-1.5 py-0.5 rounded border border-slate-200 dark:border-slate-600">{s}</span>
                       ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Stats Column */}
          <div className="space-y-6">
             <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6 flex flex-col items-center border border-slate-200 dark:border-slate-700">
               <div className="relative w-40 h-40 flex items-center justify-center mb-4">
                 <svg className="w-full h-full transform -rotate-90">
                   <circle cx="80" cy="80" r="70" stroke={darkMode ? "#334155" : "#f1f5f9"} strokeWidth="10" fill="transparent" />
                   <circle cx="80" cy="80" r="70" stroke="#0891b2" strokeWidth="10" fill="transparent" 
                     strokeDasharray={440} strokeDashoffset={440 - (440 * report.overallScore / 100)} 
                   />
                 </svg>
                 <span className="absolute text-3xl font-bold text-slate-800 dark:text-white">{report.overallScore}</span>
               </div>
               <p className="text-sm text-slate-500 dark:text-slate-400 font-medium uppercase tracking-wide">Overall Match Score</p>
             </div>

             <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-700">
                <h3 className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase mb-4 text-center">Skill Distribution</h3>
                <div className="h-64 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <RadarChart cx="50%" cy="50%" outerRadius="80%" data={chartData}>
                      <PolarGrid stroke={darkMode ? "#475569" : "#cbd5e1"} />
                      <PolarAngleAxis dataKey="subject" tick={{fontSize: 10, fill: darkMode ? '#cbd5e1' : '#475569'}} />
                      <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} />
                      <Radar name="Candidate" dataKey="A" stroke="#0891b2" fill="#06b6d4" fillOpacity={0.6} />
                    </RadarChart>
                  </ResponsiveContainer>
                </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportStage;